version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-cargo-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Packages
          command: sudo apt update && sudo apt install libsdl2-dev
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Lint
          command: rustup component add rustfmt && cargo fmt --all -- --check
      - save_cache:
          key: v1-cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo

workflows:
  version: 2
  build:
    jobs:
      - build

